apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-backend-northstar-dev
  namespace: northstar-backend-dev
  annotations:
    azure.workload.identity/client-id: "09cdccd0-38df-4992-9e4d-3258881b6d3c"
