apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: northstar-backend-keyvault
  namespace: northstar

spec:
  provider: azure

  secretObjects:
    - secretName: northstar-backend-secrets
      type: Opaque
      data:
        - objectName: database-url
          key: DATABASE_URL

  parameters:
    usePodIdentity: "false"

    clientID: "09cdccd0-38df-4992-9e4d-3258881b6d3c"

    keyvaultName: "kv-northstar-dev0001"

    cloudName: ""

    objects: |
      array:
        - |
          objectName: database-url
          objectType: secret
          objectVersion: ""

    tenantId: "b59f427b-0ce3-4edb-b2ec-870be17da01b"
