name: Build and Push Images

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  ACR_NAME: northstarlogisticsdevacr
  ACR_LOGIN_SERVER: northstarlogisticsdevacr.azurecr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: |
          az acr login --name "$ACR_NAME"

      - name: Build backend image
        run: |
          docker build \
            -t $ACR_LOGIN_SERVER/northstar-backend:${{ github.sha }} \
            application/backend

      - name: Build frontend image
        run: |
          docker build \
            -t $ACR_LOGIN_SERVER/northstar-frontend:${{ github.sha }} \
            application/frontend

      - name: Push backend image
        run: |
          docker push \
            $ACR_LOGIN_SERVER/northstar-backend:${{ github.sha }}

      - name: Push frontend image
        run: |
          docker push \
            $ACR_LOGIN_SERVER/northstar-frontend:${{ github.sha }}